name: tdd_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^0.0.1+3
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  
  uses-material-design: true
